### ISSUE TITLE
Using default keybindings, GTK_CSD=1 etc.

### ISSUE THREAD

**Issue by marlock9** [decathorpe/pantheon-session-settings#6]
Just a question to clarify reasons of cutting stuff from pantheon default-settings (https://github.com/elementary/default-settings)
Why did you cut out keybindings and all other sections except just GTK settings from (https://github.com/decathorpe/pantheon-session-settings/blob/master/overrides/20-io.elementary.desktop.gschema.override) file?
Why don't you use profile.d files from upstream including one enabling GTK_CSD=1?

**Comment by decathorpe** [comment]
That was a pretty arbitrary decision - I looked at the overrides and decided what made sense in the scope of a fedora package, and what doesn't. So really, the contents of the overrides file can be changed as needed, if there are issues.

Also I can't use profile.d files in fedora, because I don't want to override the distro's default settings here - if there's a Pantheon edition of fedora in the future, that would be different, of course. Also, GTK_CSD=1 should be the default behaviour of GTK in fedora for some releases already.

**Comment by marlock9** [comment]
This package doesn't install with `sudo dnf group install "Pantheon Desktop"`. 
So, if there are people who really want to get elementary OS' genuine experience (like me), they should find out this package (because it existence is simply not mentioned in https://decathorpe.com/2019/05/07/pantheon-fedora-30-guide.html) and install it manually. Why not to give all of those stuff to such people? They know what they want and do all the package research with clear purposes. Now such people may be frustrated because they won't get even the eOS keybindings.
P.S. I haven't GTK_CSD=1 in Fedora 30 Workstation by default.
P.P.S. I have some issues with another packages, e.g. plank, where should I post them?

**Comment by decathorpe** [comment]
That's clearly a trade-off in my opinion - because the overrides also override settings in other gtk-based desktop environments, primarily GNOME, which is probably unexpected if you don't know how the lower levels of the Pantheon stack works. That's also the reason why the overrides package is not part of the Pantheon Desktop package group, and why I don't recommend it to users.

**Comment by decathorpe** [comment]
Additional info:

- GTK_CSD environment variable is not set on fedora because it should not be necessary. What do you hope to gain by explicitly setting this?

- I think the keybindings on elementary would rather confuse people than help newcomers, because they made some "interesting" decisions there in my opinion. But you are right, for users who are already used to Pantheon on elementaryOS, I could provide a way to override the default behavior.

- I am aware that plank has some issues, and most of them are not specific to fedora. As such, you can either report them on the Red Hat BugZilla instance under the "Fedora" Product and "plank" component (for issues specific to fedora) or on the upstream plank project in launchpad.net for issues that happen on elementaryOS as well.

**Comment by marlock9** [comment]
- Without CSD decorations on some windows looks ugly (for example - shutdown dialog).
- I have some research about plank and found that using latest git version solves main problems (absence of some animations and overall hyperspeed of animations). elementaryOS uses git version of plank. I didn't find package with git version of plank for fedora (started to search from your elementary-nightly copr).

**Comment by decathorpe** [comment]
>     * Without CSD decorations on some windows look ugly (for example - shutdown dialog).

Ok, that's interesting. Maybe that should be hard-coded in the elementary component itself, instead of relying on an environment variable?

>     * I have some research about plank and found that using latest git version solves main problems (absence of some animations and overall hyperspeed of animations). elementaryOS uses git version of plank (because of those bugs I'm sure). I didn't find package with git version of plank for fedora (started to search from your elementary-nightly copr).

Alright, that's fair. I could try to provide git snapshot builds of plank, but that would only be via the elementary-nightly COPR repo, and not for stable fedora packages.

**Comment by marlock9** [comment]
> Maybe that should be hard-coded in the elementary component itself, instead of relying on an environment variable?
Maybe. But I don't know reasons of enabling CSD by eOS devs (maybe you know?). Frankly, I can't remember where I saw ugly window decoration aside of shutdown dialog, but _maybe_ they know a little bit more than we and they enabled CSD to get rid of some visual inconsistency?
> I could try to provide git snapshot builds of plank, but that would only be via the elementary-nightly COPR repo, and not for stable fedora packages.
I think there is no need to build package after every commit, version used now in elementary OS would be enough. What is blocking you to update plank in stable repo to this version?

**Comment by decathorpe** [comment]
> Maybe. But I don't know reasons of enabling CSD by eOS devs (maybe you know?). Frankly, I can't remember where I saw ugly window decoration aside of shutdown dialog, but _maybe_ they know a little bit more than we and they enabled CSD to get rid of some visual inconsistency?

I will ask them.

> I think there is no need to build package after every commit, version used now in elementary OS would be enough. What is blocking you to update plank in stable repo to this version?

The plank package in the official repos is not only used by Pantheon, but is available for other desktop environments as well. I'm not even the primary maintainer of plank in fedora and only have limited privileges to deal with that package. Updating packages to development snapshots also is generally something that should not be done outside of the development branch of fedora (rawhide).

**Comment by decathorpe** [comment]
Alright, elementary devs were able to help me with the GTK_CSD thing. It **would** fix the look of dialog windows, but would break most non-GTK apps. So it's not an acceptable solution for fedora.

**Comment by marlock9** [comment]
Okay, so I will enable it manually for me.

Summarizing the above, I'm expecting to see a way to get default keybindings through package and plank package built from git snapshot.

Thank you for your great work. Pantheon on Fedora feels much stable than even on the elementary OS.

**Comment by decathorpe** [comment]
I've prepared updates for gala and pantheon-session-settings to fix some of the issues.

And I've re-enabled snapshot builds of plank for the elementary-nightly repo.

**Comment by decathorpe** [comment]
With the latest update for wingpanel-indicator-session, the logout and shutdown dialogs should look as intended as well, without having to set GTK_CSD=1.
